/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const FileMetadata = IDL.Record({
  'id' : ExternalBlob,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'blobId' : ExternalBlob,
  'uploadedAt' : Time,
  'uploadedBy' : IDL.Principal,
});
export const Device = IDL.Record({
  'name' : IDL.Text,
  'isConnected' : IDL.Bool,
});
export const TransferRecord = IDL.Record({
  'status' : IDL.Variant({ 'completed' : IDL.Null, 'failed' : IDL.Null }),
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'sender' : IDL.Principal,
  'transferredAt' : Time,
  'receiver' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNearbyDevice' : IDL.Func([IDL.Text], [], []),
  'addTransferRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Variant({ 'completed' : IDL.Null, 'failed' : IDL.Null }),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'connectToDevice' : IDL.Func([IDL.Text], [], []),
  'deleteFile' : IDL.Func([ExternalBlob], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFileById' : IDL.Func([ExternalBlob], [FileMetadata], ['query']),
  'getMyFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getNearbyDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
  'getTransferHistory' : IDL.Func([], [IDL.Vec(TransferRecord)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
      [ExternalBlob],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const FileMetadata = IDL.Record({
    'id' : ExternalBlob,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'blobId' : ExternalBlob,
    'uploadedAt' : Time,
    'uploadedBy' : IDL.Principal,
  });
  const Device = IDL.Record({ 'name' : IDL.Text, 'isConnected' : IDL.Bool });
  const TransferRecord = IDL.Record({
    'status' : IDL.Variant({ 'completed' : IDL.Null, 'failed' : IDL.Null }),
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'sender' : IDL.Principal,
    'transferredAt' : Time,
    'receiver' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNearbyDevice' : IDL.Func([IDL.Text], [], []),
    'addTransferRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Variant({ 'completed' : IDL.Null, 'failed' : IDL.Null }),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'connectToDevice' : IDL.Func([IDL.Text], [], []),
    'deleteFile' : IDL.Func([ExternalBlob], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFileById' : IDL.Func([ExternalBlob], [FileMetadata], ['query']),
    'getMyFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getNearbyDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
    'getTransferHistory' : IDL.Func([], [IDL.Vec(TransferRecord)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
        [ExternalBlob],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };