/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Device { 'name' : string, 'isConnected' : boolean }
export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : ExternalBlob,
  'fileName' : string,
  'fileSize' : bigint,
  'fileType' : string,
  'blobId' : ExternalBlob,
  'uploadedAt' : Time,
  'uploadedBy' : Principal,
}
export type Time = bigint;
export interface TransferRecord {
  'status' : { 'completed' : null } |
    { 'failed' : null },
  'fileName' : string,
  'fileSize' : bigint,
  'sender' : Principal,
  'transferredAt' : Time,
  'receiver' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNearbyDevice' : ActorMethod<[string], undefined>,
  'addTransferRecord' : ActorMethod<
    [string, string, bigint, { 'completed' : null } | { 'failed' : null }],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'connectToDevice' : ActorMethod<[string], undefined>,
  'deleteFile' : ActorMethod<[ExternalBlob], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileById' : ActorMethod<[ExternalBlob], FileMetadata>,
  'getMyFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getNearbyDevices' : ActorMethod<[], Array<Device>>,
  'getTransferHistory' : ActorMethod<[], Array<TransferRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'uploadFile' : ActorMethod<
    [string, bigint, string, ExternalBlob],
    ExternalBlob
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];